### ISSUE TITLE
Crash after recent Minecraft client update

### ISSUE THREAD

**Issue by Belayabelka** [tracer4b/nomi-ceu#145]
**Pack Version:**
nomi-ceu-client-1.4.1a

**Description:**
Everything was alright two days ago then i got this problem. The only thing different is that minecraft client was updated when i launched the modpack.

**Crash Log:**
https://pastes.dev/KrPxR4sDBX
**Screenshots:**

![Снимок экрана (123)](https://user-images.githubusercontent.com/117731907/200555712-cd17985c-40b7-42c5-a344-41b50f6b9265.png)

**Comment by Boud811** [comment]
same here

**Comment by MadMedicineMan** [comment]
Got the same problem.

More specifically, it seems that the content tweaker bounties and rewards are the problem. (The crash log specifically identifies the wood, stone, alloy, and ender widgets), and the rewards. If you remove these bounties from the bounties,json and leave just [] in rewards.json, the game starts normal. 

However, without the rewards theres very little reason to have the bounties. 

[rewards.txt](https://github.com/tracer4b/nomi-ceu/files/9963627/rewards.txt)
[bounties.txt](https://github.com/tracer4b/nomi-ceu/files/9963628/bounties.txt)

(Edited files, file changed to .txt because github)

Very strange issue.

**Comment by MadMedicineMan** [comment]
NVM, it gets even stranger. When editing the bountiful files to be able to start the game, loading into the world gives this message;

![image](https://user-images.githubusercontent.com/65600900/200633533-061c1fe1-a556-48d4-b1cf-4bc9e73aa413.png)

There is something very strange going on that broke the pack. And i dont get how a simple launcher update did this.

**Comment by Belayabelka** [comment]
By the way, why Minecraft Forge and Forge Mod Loader marked as different mods? Is this okay?

**Comment by Pelotrio** [comment]
Yes the launcher is definitely at fault here due to the launcher issues contentweaker basically breaks completely. if you use alternative launchers like gdlauncher it works as normal.

**Comment by Folanlron** [comment]
This is a CF issue and is completely out of everyones hands.. It's all up to them to fix it.

**Comment by Belayabelka** [comment]
They've fixed it! Pretty fast
