### ISSUE TITLE
Adding in progression line for AR

### ISSUE THREAD

**Issue by wedgevic** [tracer4b/nomi-ceu#301]
Hiya,
I just got to the point that I could finally delve deep into Advanced Rocketry in the pack, but I noticed that most of the multiblocks, items and mechanics are completely disabled in the pack. Is there a reason for this or has AR just been too finicky to work with? 

Thank you for your help.

P.S. I have also been testing the latest version of AR and LibVulpes in the pack with some success, the only takeaway being that you'll want to make a world edit schematic of your space station, as that is completely wiped with the update, as I almost learnt the hard way. Besides that everything works fine.

**Comment by IntegerLimit** [comment]
I'm not sure, ask Exa in #packdeveloperchat in our discord. I honestly have no idea. The question is also better suited there. If your not in the discord server, there's a link either in the README of this GitHub, or there's also a link on the title screen, in-game.

Lib Vulpes will not be updated, due to a crash in Gas Oxygen Pad in newer versions of Lib Vulpes. I was wondering why AR wasn't updated, so thank you for answering my question. Based on that, AR will also not be updated, anytime in the future.

**Comment by wedgevic** [comment]
Alright, thank you
